/**
 * Contract configuration for PrivateZK Credit Scout
 * Auto-generated - do not edit manually
 * Run 'npm run integrate:frontend' from contracts directory to update
 */

// Contract addresses from environment variables
export const VERIFIER_ADDRESS = import.meta.env.VITE_VERIFIER_ADDRESS as `0x${string}` | undefined;
export const PRIVATE_CREDIT_LENDING_ADDRESS = import.meta.env.VITE_PRIVATE_CREDIT_LENDING_ADDRESS as `0x${string}` | undefined;

// Network configuration
export const NETWORK_CHAIN_ID = import.meta.env.VITE_NETWORK_CHAIN_ID 
  ? parseInt(import.meta.env.VITE_NETWORK_CHAIN_ID) 
  : 5003;

export const EXPLORER_URL = import.meta.env.VITE_EXPLORER_URL || 'https://explorer.sepolia.mantle.xyz';

// Contract ABI imports (will be generated by integration script)
export { default as PrivateCreditLendingABI } from './PrivateCreditLending.json';
export { default as VerifierABI } from './Verifier.json';

